controller:
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  tag: "lts-jdk17"
  serviceType: ClusterIP
  admin:
    username: "admin"
    password: "admin123"
  installPlugins:
    - kubernetes:4013.v1a_0a_4367b_f82f"
    - workflow-job:1289.vd1c337fd5354"
    - command-launcher:108.v14d7c66525ee"
  persistence:
    enabled: true
    storageClass: "standard"
    size: 8Gi
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"

agent:
  enabled: true
  podName: "jenkins-agent"
  image: "jenkins/inbound-agent"
  tag: "alpine"
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "1024m"
      memory: "1024Mi"

persistence:
  enabled: true
  storageClass: "standard"